import type { ApiLog, ApiSession } from '../models';

export const generateHtmlReport = (
  session: ApiSession,
  senderName?: string
): string => {
  const totalRequests = session.logs.length;
  const successRequests = session.logs.filter(
    (log: ApiLog) => !log.isError
  ).length;
  const failureRequests = totalRequests - successRequests;
  const successRate =
    totalRequests > 0
      ? ((successRequests / totalRequests) * 100).toFixed(1)
      : '0.0';

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 40px 20px; background-color: #f9f9f9; }
    .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.05); }
    .header { background-color: #6200ee; color: white; padding: 30px; text-align: center; }
    .content { padding: 40px; }
    .stat-card { background-color: #f8f9fa; padding: 20px; border-radius: 12px; text-align: center; border: 1px solid #eee; }
    .stat-value { font-size: 32px; font-weight: 800; color: #6200ee; margin-bottom: 4px; }
    .stat-label { font-size: 11px; font-weight: 700; color: #888; text-transform: uppercase; letter-spacing: 1px; }
    .info-section { border-top: 1px solid #eee; padding-top: 25px; margin-top: 20px; }
    .info-table { width: 100%; border-collapse: collapse; }
    .info-label { color: #666; font-size: 13px; padding: 6px 0; width: 120px; }
    .info-value { font-weight: 700; color: #333; font-size: 14px; padding: 6px 0; text-align: left; }
    .footer { padding: 20px; font-size: 11px; color: #aaa; text-align: center; background-color: #fafafa; }
    .success-text { color: #43a047 !important; }
    .error-text { color: #e53935 !important; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1 style="margin: 0; font-size: 24px; letter-spacing: -0.5px;">Session Summary</h1>
      <p style="margin: 8px 0 0 0; font-size: 14px; opacity: 0.9;">${session.name}</p>
    </div>
    
    <div class="content">
      <div style="display: table; width: 100%; border-spacing: 15px; margin-left: -15px; margin-right: -15px;">
        <div style="display: table-row;">
          <div style="display: table-cell; width: 50%;">
            <div class="stat-card">
              <div class="stat-value">${totalRequests}</div>
              <div class="stat-label">Total Requests</div>
            </div>
          </div>
          <div style="display: table-cell; width: 50%;">
            <div class="stat-card">
              <div class="stat-value" style="color: #6200ee;">${successRate}%</div>
              <div class="stat-label">Success Rate</div>
            </div>
          </div>
        </div>
        <div style="display: table-row;">
          <div style="display: table-cell; width: 50%;">
            <div class="stat-card">
              <div class="stat-value success-text">${successRequests}</div>
              <div class="stat-label">Successful</div>
            </div>
          </div>
          <div style="display: table-cell; width: 50%;">
            <div class="stat-card">
              <div class="stat-value error-text">${failureRequests}</div>
              <div class="stat-label">Failures</div>
            </div>
          </div>
        </div>
      </div>

      <div class="info-section">
        <table class="info-table">
          ${
            senderName
              ? `
          <tr>
            <td class="info-label">Sent By</td>
            <td class="info-value">${senderName}</td>
          </tr>`
              : ''
          }
          <tr>
            <td class="info-label">Started At</td>
            <td class="info-value">${new Date(session.startTime).toLocaleString()}</td>
          </tr>
          <tr>
            <td class="info-label">Session ID</td>
            <td class="info-value" style="font-family: monospace;">${session.id}</td>
          </tr>
        </table>
      </div>
      
      <p style="margin-top: 35px; font-size: 13px; color: #777; text-align: center; font-style: italic;">
        A full detailed log report is attached as a <b>.txt</b> file for your inspection.
      </p>
    </div>
    
    <div class="footer">
      Generated by React Native API Logger • 2026
    </div>
  </div>
</body>
</html>
  `;
};
